services:

  api:
    image: guilhermeasilva/swarm:latest
    ports:
      - "3000:3000"
    networks:
      - nginx_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  nginx_network:
    external: true